export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const GET_BASKET = 'GET_BASKET';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const DELETE_ITEM = 'DELETE_ITEM';